### ISSUE TITLE
Would this work with HD-PVR for capture?

### ISSUE THREAD

**Issue by Gribnif** [bennettpeter/MythTV-LeanCapture#1]
I'm intrigued by the possibility of using your scripts to capture things from a FireStick 4K. In my case, I already have two original HD-PVRs that will be sitting unused once I cancel my satellite dish subscription. Do you think it would work to use one of them to capture the FireStick's HDMI output, rather than buying one of the capture dongles you suggest? Would I still tell Myth I'm using an HD-PVR, or would I tell your scripts to capture directly from the /dev/videoX device?

**Comment by bennettpeter** [comment]
I don't know much about the HD-PVR. I believe the original HD-PVR only had component inputs. I don't know whether you could capture its output in the same way.

The scripts are designed for Comcast / xfinity, if you want to use them for another provider you will need to make some changes.

**Comment by Gribnif** [comment]
You are, of course, right about the HD-PVR lacking HDMI an input. I hadn't looked at them in so long that detail slipped my mind. Looks like I'm going to be using another capture card I already have, instead.

Thanks for the response.
