### ISSUE TITLE
unknown input format

### ISSUE THREAD

**Issue by yajrendrag** [bennettpeter/MythTV-LeanCapture#2]
running leanfire.sh on non-myth system.  i did the install using my own userid prepending `MYTHTVUSER=<user> MYTHTVGROUP=<group>` in the install command.

i tried both leanrec and leanfire and neither of them make a recording.  So, i tried leanfire using the --nowait option where i manually press the ok button on the remote.

this is the output i got:

```
2024-10-09_11-19-13 Start of run ***********************
2024-10-09_11-19-13 Record for 44 minutes and respond 0 times.
connected to 192.168.1.107:5555
192.168.1.107:5555	device
13699
2024-10-09_11-19-15 Starting recording of 2024-10-09_11-19-15
DPAD_CENTER (23)
Unknown input format: 'alsa'
ioctl(VIDIOC_QBUF): Bad file descriptor
2024-10-09_11-20-17 ffmpeg terminated
2024-10-09_11-20-17 Playback finished
2024-10-09_11-20-17 Exit
HOME (3)
```
i know the ./adb-sendkey.sh DPAD_CENTER is working because i tried it from the command line, but without the nowait option and manual button press, nothing happes, it is terminating before anything else happens.

Seems like it's having an issue w/ my audio setup.  This is an ubuntu 22.04 system but i used this: `https://ubuntuhandbook.org/index.php/2022/04/pipewire-replace-pulseaudio-ubuntu-2204/` to install pipewire.  not sure if that is having an impact here...

EDIT - i do see that ffmpeg -devices does not list an alsa device...

EDIT 2 - it appears to be an issue w/ the ffmpeg package i installed...

**Comment by yajrendrag** [comment]
still not working... but some slight further progress.  it produces a captured mkv now (but only when using --nowait), but it's a still image.  it still doesn't push the button, so i have to use --nowait, but as soon as i do that, vlc quits and it records a whatever image was last on the screen until it detects it's on pause and then stops.

```
2024-10-09_12-47-13 Start of run ***********************
2024-10-09_12-47-13 Record for 44 minutes and respond 0 times.
connected to 192.168.1.107:5555
192.168.1.107:5555	device
86564
2024-10-09_12-47-16 Starting recording of 2024-10-09_12-47-16
DPAD_CENTER (23)
2024-10-09_12-48-17 size: 1048576  Incr: 1048576
2024-10-09_12-48-17 Less than 5000000, lowcount=1
2024-10-09_12-49-18 size: 2359296  Incr: 1310720
2024-10-09_12-49-18 Less than 5000000, lowcount=2
2024-10-09_12-50-18 size: 3670016  Incr: 1310720
2024-10-09_12-50-18 Less than 5000000, lowcount=3
2024-10-09_12-51-19 size: 4980736  Incr: 1310720
2024-10-09_12-51-19 Less than 5000000, lowcount=4
2024-10-09_12-52-19 Playback paused too long
2024-10-09_12-52-19 Playback finished
2024-10-09_12-52-19 Exit
HOME (3)
```

still can't get leanrec to record anything - it detects what is on the screen via adb, echos it in text format to the log, then Exists & quits.  no captured output is produced

`*****`
2024-10-09_13-24-03 Exit
HOME (3)
disconnected 192.168.1.107

**Comment by bennettpeter** [comment]
Here are some suggestions:

I have not used leanfire for some time, so there may be problems with it. leanrec provides everything needed to record from many streaming services, and that is what I use currently for any streaming service I want to record.

Some builds of ffmpeg do not have the correct drivers built in. I just use "sudo apt install ffmpeg" on ubuntu (currently 24.04). I seem to remember trying an ffmpeg from a PPA and having a problem.

Did you run leancap_scan, and was it successful??

Can you run leanvlc.sh and see the fire tv in the vlc window? Note that the vlc that comes with ubuntu 22.04 has a bug where it cannot play the audio from the usb stick and fails with an error. The vlc installed with apt in 24.04 is good. The vlc installed via snap did not work for this.

For it to record audio, the capture device needs to be excluded from pipewire and pulseaudiio, so you need the /etc/udev/rules.d/89-pulseaudio-usb.rules installed and to reboot.

The scripts cannot record while vlc is displaying the picture, so you need to close vlc before you start recording. There is code to close vlc when you use wait. If you don't use wait, leanfrec needs you close vlc yourself.

**Comment by yajrendrag** [comment]
leancap_scan was successful. yes, i can run leanvlc.sh and see firetv in vlc - just no sound in vlc on ubuntu 22.04)..  But, it does work if i use --nowait with leanfire, start the video and then close vlc.  and i have audio.  if i remove --nowait, the button is not pressed, VLC does not close and nothing is recorded.  leanrec doesn't work either - it just closes after a few seconds nothing recorded.

**Comment by bennettpeter** [comment]
I don't know why the button press would not be working.
chack your adb version (type adb version). I get this from adb version:
```
Android Debug Bridge version 1.0.41
Version 35.0.1-11580240
Installed as /usr/local/bin/adb
Running on Linux 6.8.0-45-generic (x86_64) 
```
Try this. 
run vlc.sh. You should see vlc with your fire tv screen displayed. While it is open run the following. You may have to add the path in front of the adb-sendkey.sh:
```
adb connect <fire tv ip address>
adb-sendkey.sh RIGHT
adb-sendkey.sh RIGHT RIGHT
```
When you run the adb-sendkey.sh RIGHT you should see the selection on the fire stick move to the right, or twice to the right when you do RIGHT RIGHT. Try adb-sendkey.sh DPAD_CENTER . That should send an enter keystroke.

You can also try adb-sendkey.sh without a parameter and see a menu of button presses you can use.  This requires zenity installed on  your system. Double click an item to send that key code. Try them out and see if they work and control your fire stick.

**Comment by yajrendrag** [comment]
same adb version.  the adb-sendkey.sh commands work.  But this is odd - i had already gone through the step where i got the prompt to allow adb debugging access to the device any time it connects from this machine... but i just got it again.  I know you have to rerun leancap_scan when the device is replugged or after a reboot, but should it lose the forever adb setting?

Still nothing works - neither leanfire or leanrec will press the button.  leanrec does something to cause the device to go home and not into the video to play and record it.  script terminates.

leanfire with nowait set will work.  thats it.  I suppose i will try it with mythtv... this just doesn't seem to work or i am doing something really dumb and just overlooking something...

**Comment by yajrendrag** [comment]
making some progress now.  i set up a 2nd machine - different capture card.  but same results.  but after re-reading, i think i know why the script isn't sending the DPAD_CENTER... nothing i'm recording has an actual play button.  they all say something else or nothing (you just select continue watching & it plays).  if i am right about that, then my work around is to build it into my own script in which i call leanrec.sh which i run without wait.  so after doing that it works.  now i just can't figure out how to get the recording to stop.  it always goes to the maximum time... i tried with & without textoverlay, but no difference.   any pointers?

**Comment by bennettpeter** [comment]
- With leanrec you need to make sure that the cursor is positioned on the play button or continue watching button or whatever, then when the script sends the DPAD_CENTER it starts playing or resumes playing.
- There is also the --playing option that can be used if it is already playing when you start. Then it does not send the DPAD_CENTER.
- As far as stopping is concerned, there are different options depending on the streaming service. Running leanrec without parameters displays the options.
- If it detects textoverlay or you set it, then it will only stop on particular text seen, such as "BACK TO BROWSE" or "Up Next". If the service is displaying some sort of text message like that you can specify it with the endtext option (Note you may have to install the latest version of leancap, I only added the endtext parameter a week ago).
- If it does not detect textoverlay and iyou do not set it, it ends with the first time text is detected.
- When all else fails, use the -s option to stop after a fixed time.
- If you give me your email address I can send you my notes for a bunch of streaming services. I do not want to post that publicly.

**Comment by yajrendrag** [comment]
email sent via github...

endtext is supposed to have a default, but if i leave it off i get an error that it's missing... i just added your defined default.  is endtext intended to be a standalone option or is it intended to follow textoverlay?  without textoverlay, it didn't seem to do anything and the default regex has several of the text strings that i see upon conclusion of playing..

textoverlay also seems to be a cause of  leanrec not recording.  it seems to stop immediately when i specify that as there is text on the screen at the start.  Also, i did some further experimenting - in addition to leaving out textoverlay, it seems that I need more delay between DPAD_CENTER being issued by leanrec and the start of ffmpeg.    i added a sleep 5 in the script and that seemed to let it progress and record.

**Comment by bennettpeter** [comment]
If you specify --endtext without a value after it in the command line you will get an error that the value is missing. If you leave --endtext off the command line it will take the default value. The order of parameters is not important, but after a parameter that takes a value the next parameter must be the value. I don't know why you need a delay. What happens without the delay? Does it stop or do you get an empty recording?

I did not get your email address. You can email me peterbenn1 at gmail.com

**Comment by yajrendrag** [comment]
understood, thanks.  ignore my comment about delay - sorry,  that is what i did to make leanfire.sh work.  with leanrec.sh it still doesn't press any buttons.  the only way it seems to work for me is to start playing and immediately press pause.  then leacnrec.sh correctly sends the DPAD_CENTER and the video resumes and then things work fine...
